-- Historical contact links on company-scoped activities/tasks are intentionally
-- preserved. The UI treats links to deleted or otherwise inactive contacts as
-- non-clickable historical names so activity history still shows who we spoke
-- with, without listing that person as an active CRM contact.
